# Generated by Django 5.0.6 on 2024-06-02 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='current_time',
            field=models.DateTimeField(default=1),
            preserve_default=False,
        ),
    ]
