# Generated by Django 5.0.6 on 2024-06-02 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_post_current_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='current_time',
        ),
        migrations.AddField(
            model_name='post',
            name='upload_date',
            field=models.DateTimeField(default=1),
            preserve_default=False,
        ),
    ]
