# Generated by Django 5.0.6 on 2024-06-02 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_remove_post_current_time_post_upload_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='upload_date',
        ),
    ]
